import praw
f = open(r"C:\Users\stein\Desktop\genericPassword.txt", "r")
genericPassword = f.read()
f.close()

class NameGenned5 :
    __client_id = "roNVv-oS-FrMnw"
    __client_secret = "A1AgMgGdND_qM-nJZed4QEZLmog"
    def __init__(self, name):
        self.name = name
                
                
    _canad8an_weed = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'canad8an-weed',
                             username = 'canad8an-weed',
                             password = genericPassword)
    _kazingaAM5 = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'kazingaAM5',
                             username = 'kazingaAM5',
                             password = genericPassword)
    _Hellothi3isfullstop = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'Hellothi3isfullstop',
                             username = 'Hellothi3isfullstop',
                             password = genericPassword)
    _ebuitron35 = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'ebuitron35',
                             username = 'ebuitron35',
                             password = genericPassword)
    _koal8joey = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'koal8joey',
                             username = 'koal8joey',
                             password = genericPassword)
    _Mi9dofthelion = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'Mi9dofthelion',
                             username = 'Mi9dofthelion',
                             password = genericPassword)
    _douev5nwheelanddeal = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'douev5nwheelanddeal',
                             username = 'douev5nwheelanddeal',
                             password = genericPassword)
    _joyfulmast7rmind = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'joyfulmast7rmind',
                             username = 'joyfulmast7rmind',
                             password = genericPassword)
    _Ma9ginal_act = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'Ma9ginal_act',
                             username = 'Ma9ginal_act',
                             password = genericPassword)
    _butt3pigot = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'butt3pigot',
                             username = 'butt3pigot',
                             password = genericPassword)
    _Caligari21023 = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'Caligari21023',
                             username = 'Caligari21023',
                             password = genericPassword)
    _nman7510 = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'nman7510',
                             username = 'nman7510',
                             password = genericPassword)
    _faivulnerab6e = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'faivulnerab6e',
                             username = 'faivulnerab6e',
                             password = genericPassword)
    _kami2azemonk = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'kami2azemonk',
                             username = 'kami2azemonk',
                             password = genericPassword)
    _Mitch5e = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'Mitch5e',
                             username = 'Mitch5e',
                             password = genericPassword)
    _SpanishChann6l = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'SpanishChann6l',
                             username = 'SpanishChann6l',
                             password = genericPassword)
    _daddy7288 = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'daddy7288',
                             username = 'daddy7288',
                             password = genericPassword)
    _garicula26 = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'garicula26',
                             username = 'garicula26',
                             password = genericPassword)
    _Devil31093 = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'Devil31093',
                             username = 'Devil31093',
                             password = genericPassword)

    ### Definitions
    All = [_canad8an_weed,_kazingaAM5,_Hellothi3isfullstop,_ebuitron35,_koal8joey,_Mi9dofthelion,_douev5nwheelanddeal,_joyfulmast7rmind,_Ma9ginal_act,_butt3pigot,_Caligari21023,_nman7510,_faivulnerab6e,_kami2azemonk,_Mitch5e,_SpanishChann6l,_daddy7288,_garicula26,_Devil31093]
    ###

print("NameGenned5: \t\t", NameGenned5.All.__len__())