import praw
f = open(r"C:\Users\stein\Desktop\genericPassword.txt", "r")
genericPassword = f.read()
f.close()

class NameGenned6 :
    __client_id = "YWG8eYJsvtTuFg"
    __client_secret = "tUuRNUirGe7DkD2uBXO2CzDorZM"

    def __init__(self, name):
        self.name = name
                

    _r7__it = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'r7--it',
                             username = 'r7--it',
                             password = genericPassword)
    _Ac8romNy = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'Ac8romNy',
                             username = 'Ac8romNy',
                             password = genericPassword)
    _Who0lesh = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'Who0lesh',
                             username = 'Who0lesh',
                             password = genericPassword)
    _RateMyMa7or = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'RateMyMa7or',
                             username = 'RateMyMa7or',
                             password = genericPassword)
    _no2emberjorge = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'no2emberjorge',
                             username = 'no2emberjorge',
                             password = genericPassword)
    _Parky_3arky = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'Parky-3arky',
                             username = 'Parky-3arky',
                             password = genericPassword)
    _iginkoo2108x = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'iginkoo2108x',
                             username = 'iginkoo2108x',
                             password = genericPassword)
    _modot77 = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'modot77',
                             username = 'modot77',
                             password = genericPassword)
    _n9toxic32 = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'n9toxic32',
                             username = 'n9toxic32',
                             password = genericPassword)
    _Doctor_Clion2 = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'Doctor_Clion2',
                             username = 'Doctor_Clion2',
                             password = genericPassword)
    _ryry104810 = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'ryry104810',
                             username = 'ryry104810',
                             password = genericPassword)
    _alexisfine6se = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'alexisfine6se',
                             username = 'alexisfine6se',
                             password = genericPassword)
    _ROOSTERBOY463 = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'ROOSTERBOY463',
                             username = 'ROOSTERBOY463',
                             password = genericPassword)
    _icel3o = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'icel3o',
                             username = 'icel3o',
                             password = genericPassword)
    _ka106102106 = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'ka106102106',
                             username = 'ka106102106',
                             password = genericPassword)
    _Invincib3eBird = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'Invincib3eBird',
                             username = 'Invincib3eBird',
                             password = genericPassword)
    _CompliantMonk67 = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'CompliantMonk67',
                             username = 'CompliantMonk67',
                             password = genericPassword)
    _Mr0wld = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = 'Mr0wld',
                             username = 'Mr0wld',
                             password = genericPassword)
    _1orpina = praw.Reddit(client_id=__client_id,
                             client_secret = __client_secret,
                             user_agent = '1orpina',
                             username = '1orpina',
                             password = genericPassword)
    ### Definitions
    All = [_r7__it,_Ac8romNy,_Who0lesh,_RateMyMa7or,_no2emberjorge,_Parky_3arky,_iginkoo2108x,_modot77,_n9toxic32,_Doctor_Clion2,_ryry104810,_alexisfine6se,_ROOSTERBOY463,_icel3o,_ka106102106,_Invincib3eBird,_CompliantMonk67,_Mr0wld,_1orpina]
    ###

print("NameGenned6: \t\t", NameGenned6.All.__len__())